AWSTemplateFormatVersion: 2010-09-09
Description: "Create a Cost Alert in AWS"
Parameters: 
  MonthlyBudget: 
    Description: Expected cost per month (default 100 usd).
    Type: Number
    MinValue: 1
    Default: 100
  Threshold1:
    Description: First threshold (default 50% of budget).
    Type: Number
    MinValue: 1
    MaxValue: 2000
    Default: 50
  Threshold2:
    Description: Second threshold (default 90% of budget).
    Type: Number
    MinValue: 1
    MaxValue: 2000
    Default: 90
  Email1: 
    Description: First email address to send alert.
    Type: String
    AllowedPattern: '\S+@\S+\.\S+'
    MinLength: 5
  Email2: 
    Description: Another email address to send alert.
    Type: String
    AllowedPattern: '\S+@\S+\.\S+'
    MinLength: 5
Resources:
  MonthlyBudget:
    Type: "AWS::Budgets::Budget"
    Properties:
      Budget:
        BudgetLimit:
          Amount: !Ref MonthlyBudget
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref Threshold1
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email1
            - SubscriptionType: EMAIL
              Address: !Ref Email2
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref Threshold2
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email1
            - SubscriptionType: EMAIL
              Address: !Ref Email2
Outputs:
  BudgetId:
    Value: !Ref Budget1
