AWSTemplateFormatVersion: 2010-09-09
Description: "Create a Monthly Buget Cost Alert in AWS"
Parameters: 
  MonthlyBudget: 
    Description: Expected cost per month (default 100 usd).
    Type: Number
    MinValue: 1
    Default: 100
  Threshold1:
    Description: First threshold Actual (default 50% of budget).
    Type: Number
    MinValue: 1
    MaxValue: 2000
    Default: 50
  Threshold2:
    Description: Second threshold Actual (default 80% of budget).
    Type: Number
    MinValue: 1
    MaxValue: 2000
    Default: 80
  Threshold3:
    Description: Third threshold Forecasted (default 100% of budget).
    Type: Number
    MinValue: 1
    MaxValue: 2000
    Default: 100
  Threshold4:
    Description: Fourth threshold Actual (default 100% of budget).
    Type: Number
    MinValue: 1
    MaxValue: 2000
    Default: 100
  Email1: 
    Description: First email address to send alert.
    Type: String
    AllowedPattern: '\S+@\S+\.\S+'
    MinLength: 5
Resources:
  MonthlyBudgetCF1:
    Type: "AWS::Budgets::Budget"
    Properties:
      Budget:
        BudgetLimit:
          Amount: !Ref MonthlyBudget
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref Threshold1
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email1
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref Threshold2
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref Threshold3
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email1
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref Threshold4
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email1
Outputs:
  BudgetId:
    Value: !Ref MonthlyBudgetCF1
